### ISSUE TITLE
Error messages: might You please provide a guide?

### ISSUE THREAD

**Issue by nakigoe** [Developer-Deb/Arp-Spoof-Protection-System#1]
OSError: Error opening adapter: The filename, directory name, or volume label syntax is incorrect.  (123)

**Comment by Developer-Deb** [comment]
Check if you are giving the right path or not for running the program. Can you send the input command that you are giving ?
Example input - python.exe c:\arp_spoof_detector.py -i interface (Ethernet or wifi) this is for windows
Example input - python /root/arp_soof_detector.py -i interface (Ethernet or wifi) this is for linux
note - check the path if you are giving it like this way or not

**Comment by Developer-Deb** [comment]
Closing the issue due to no response
